# Generated by Django 4.2.27 on 2026-02-03 11:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('github_id', models.CharField(blank=True, db_index=True, help_text='GitHub user ID for OAuth', max_length=100, null=True, unique=True)),
                ('github_username', models.CharField(blank=True, db_index=True, help_text='GitHub username', max_length=100, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL', null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin')], db_index=True, default='student', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pr_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lines_added', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lines_removed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_contribution', models.DateTimeField(auto_now_add=True)),
                ('last_contribution', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contributions',
                'ordering': ['-last_contribution'],
            },
        ),
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_mentors', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_prs', models.IntegerField(default=0)),
                ('total_lines_added', models.IntegerField(default=0)),
                ('total_lines_removed', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Statistics',
                'verbose_name_plural': 'Global Statistics',
                'db_table': 'global_stats',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, help_text='Current organization/company', max_length=200)),
                ('expertise', models.CharField(help_text='Areas of expertise (comma-separated)', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Mentor bio/description', max_length=500)),
                ('experience', models.CharField(help_text='Years of experience', max_length=50)),
                ('projects_maintained', models.TextField(blank=True, help_text='List of open source projects maintained')),
                ('total_projects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['-total_projects'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(help_text='College/University name', max_length=200)),
                ('year', models.CharField(help_text='Current year of study', max_length=50)),
                ('branch', models.CharField(help_text='Branch/Department', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Student bio/description', max_length=500)),
                ('total_commits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_prs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lines_added', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lines_removed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('languages_used', models.JSONField(default=list, help_text='Programming languages used')),
                ('passed_mid_eval', models.BooleanField(default=False)),
                ('passed_end_eval', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('blog_link', models.URLField(blank=True, help_text='Personal blog or portfolio', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-total_commits'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_url', models.URLField(unique=True)),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.contribution')),
            ],
            options={
                'db_table': 'pull_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('repo_link', models.URLField(help_text='GitHub repository URL', unique=True, validators=[django.core.validators.URLValidator()])),
                ('tags', models.JSONField(default=list, help_text='Technology tags ["django", "react"]')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('tech_stack', models.JSONField(default=list, help_text='Tech stack ["Python", "JavaScript"]')),
                ('comm_channel', models.CharField(blank=True, help_text='Slack/Discord channel for project', max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('commit_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pull_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('contributors_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.mentor')),
                ('secondary_mentor', models.ForeignKey(blank=True, help_text='Optional secondary mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_projects', to='core.mentor')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(choices=[('mid', 'Mid Evaluation'), ('end', 'End Evaluation')], max_length=10)),
                ('passed', models.BooleanField(default=False)),
                ('commit_count', models.IntegerField(default=0)),
                ('pr_count', models.IntegerField(default=0)),
                ('projects_count', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.student')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.project'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.student'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('mentors', 'Mentors Only')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-total_commits', '-total_prs'], name='students_total_c_1d3d11_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['state', '-created_at'], name='pull_reques_state_eee882_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_approved', '-created_at'], name='projects_is_appr_db5894_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['difficulty'], name='projects_difficu_d0cee6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('student', 'eval_type')},
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['student', '-commit_count'], name='contributio_student_c18e25_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['project', '-pr_count'], name='contributio_project_7ca40f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('student', 'project')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['github_username'], name='users_github__5cee41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_verified'], name='users_role_a93a92_idx'),
        ),
    ]
